# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
        ('items', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Answer')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Phrase')),
                ('poll_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollUser')),
            ],
        ),
    ]
