# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerOtherQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField(verbose_name=models.Model)),
                ('otherquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.OtherQuestion')),
                ('polluser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollUser')),
            ],
        ),
    ]
