# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20171026_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase', to='items.Item'),
        ),
    ]
