# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20171027_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='items.Item'),
        ),
    ]
