# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
