# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20171022_1524'),
        ('polls', '0002_auto_20171023_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions_relation', to='competitions.Competition')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_relation', to='polls.Poll')),
            ],
        ),
    ]
