# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pollrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollrelation',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='pollrelation',
            name='poll',
        ),
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.DeleteModel(
            name='PollRelation',
        ),
    ]
