# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171027_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
